
# Example crontab to pull CSVs from Google Sheets export and cache them server side every 15 minutes, files are stored directly in the git folder but are ignored by git
# This is a very ugly example, that should be offloaded to a seperate bash script and called for cron.
#
# Systems Data for All Map
*/15 * * * * wget –no-check-certificate -b -N -q -O /var/www/map.canonn.technology/git-repos/CanonnED3D-All-Map/data/csvCache/bmSystemCache.csv 'https://docs.google.com/spreadsheets/d/e/2PACX-1vQ8QvI-CQYlDWcfyXonkisu9yUnlPNPQHgHt1_o3n0NjsFMNlRWy9EgVqFTZm8LTOWXgXp2c70GMGsr/pub?gid=0&single=true&output=csv'
*/15 * * * * wget –no-check-certificate -b -N -q -O /var/www/map.canonn.technology/git-repos/CanonnED3D-All-Map/data/csvCache/btSystemCache.csv 'https://docs.google.com/spreadsheets/d/e/2PACX-1vR_8aPljkn5ZNMUXccsySkQCDFKZlhr6WD_R3eu61fpIW-LXf4airdgzzOqgjFUkTO20SX7l7JXjYFP/pub?gid=0&single=true&output=csv'
*/15 * * * * wget –no-check-certificate -b -N -q -O /var/www/map.canonn.technology/git-repos/CanonnED3D-All-Map/data/csvCache/fgSystemCache.csv 'https://docs.google.com/spreadsheets/d/e/2PACX-1vSvvfHhzfAeDiBuQoDrnmUgeh57XjeRXWJcVe-48BW0ugulqUMDrN7AoOtY96Suk7uQHv2tcZ_ek0ty/pub?gid=1615049300&single=true&output=csv'
*/15 * * * * wget –no-check-certificate -b -N -q -O /var/www/map.canonn.technology/git-repos/CanonnED3D-All-Map/data/csvCache/fmSystemCache.csv 'https://docs.google.com/spreadsheets/d/e/2PACX-1vSlszRWQ2eTUxzzM2AxsCOnQ2Rg7C8zBx_YJGUR1BdpK-wwXv9DpeueiWEQPJTVF9AI5J3LExucx5Lh/pub?gid=827706542&single=true&output=csv'
*/15 * * * * wget –no-check-certificate -b -N -q -O /var/www/map.canonn.technology/git-repos/CanonnED3D-All-Map/data/csvCache/genSystemCache.csv 'https://docs.google.com/spreadsheets/d/e/2PACX-1vRmBzKonapgMMWeT-zc26w8xCNFvK_5l1F3fwF0_af7awhL0MNUGOKnIq4FSoEXe8TtD5HeZd4OuAUu/pub?gid=1451709127&single=true&output=csv'
*/15 * * * * wget –no-check-certificate -b -N -q -O /var/www/map.canonn.technology/git-repos/CanonnED3D-All-Map/data/csvCache/grSystemCache.csv 'https://docs.google.com/spreadsheets/d/e/2PACX-1vTYml1O4Qt2bDn9hnFJe1SeN0atyahK6dWBftGvW1YJ8b6JHBUF5WvL015_fmZF6oGkqVOGzl3mJqVI/pub?gid=756384248&single=true&output=csv'
*/15 * * * * wget –no-check-certificate -b -N -q -O /var/www/map.canonn.technology/git-repos/CanonnED3D-All-Map/data/csvCache/gySystemCache.csv 'https://docs.google.com/spreadsheets/d/e/2PACX-1vR70NkI6yp_9jwC_6FseydVBs22MrX3aWONiy4xvfx8EHz8pmI4mo1s25at8ihs3GrXRbEdoQDepy1m/pub?gid=962735107&single=true&output=csv'
*/15 * * * * wget –no-check-certificate -b -N -q -O /var/www/map.canonn.technology/git-repos/CanonnED3D-All-Map/data/csvCache/hdSystemCache.csv 'https://docs.google.com/spreadsheets/d/e/2PACX-1vSEVt8eYMJgd5vXfCMiExWc23D1G5G0DCEfs5A6N3AQGupAp1KslajioBZgB0IGiMd7MR_Ur3RPsv39/pub?gid=1013174415&single=true&output=csv'
*/15 * * * * wget –no-check-certificate -b -N -q -O /var/www/map.canonn.technology/git-repos/CanonnED3D-All-Map/data/csvCache/lsSystemCache.csv 'https://docs.google.com/spreadsheets/d/e/2PACX-1vQhAk6nZswglFQVpNpPfUwJNS0ifkN4sOLHsQeCmIrMiQM01N6tPEyvKqcHUnD-IRSO7a9bTCwa4tR6/pub?gid=220546017&single=true&output=csv'
*/15 * * * * wget –no-check-certificate -b -N -q -O /var/www/map.canonn.technology/git-repos/CanonnED3D-All-Map/data/csvCache/msSystemCache.csv 'https://docs.google.com/spreadsheets/d/e/2PACX-1vRSTnVpcJPN1yn5bcCrI3vYocYUVX08jcfsEUbbY3-u9G_uBqfGlllMu6gSa5LGt4sEO_fh3G5H2G0r/pub?gid=1120806489&single=true&output=csv'
*/15 * * * * wget –no-check-certificate -b -N -q -O /var/www/map.canonn.technology/git-repos/CanonnED3D-All-Map/data/csvCache/tbSystemCache.csv 'https://docs.google.com/spreadsheets/d/e/2PACX-1vTyFAaquLIKghHUiN-FJaku3yzGw6f_lMFQHUPqLVoCfRE8gtlWb88mMpLhoTXjLhmot0m8w9Ol5cPs/pub?gid=1613553729&single=true&output=csv'
*/15 * * * * wget –no-check-certificate -b -N -q -O /var/www/map.canonn.technology/git-repos/CanonnED3D-All-Map/data/csvCache/tsSystemCache.csv 'https://docs.google.com/spreadsheets/d/e/2PACX-1vSYvun070NwUTxemgq05M5jSrFdbJXDd3unpohkt9WhlGjHfY67odla933_HWT1xe8X5-Ebq73gz61e/pub?gid=926585382&single=true&output=csv'
*/15 * * * * wget –no-check-certificate -b -N -q -O /var/www/map.canonn.technology/git-repos/CanonnED3D-All-Map/data/csvCache/ussSystemCache.csv 'https://docs.google.com/spreadsheets/d/e/2PACX-1vQM1TtPi_18DZ0hIJ2dW44F0BpW6_igwfXYbTuZS3IQZUIjmZLY5ElZFuWpLES7iBQNDsVs8vwXwJ1n/pub?gid=1735934279&single=true&output=csv'
#
#
# All data for Detailed Maps
*/15 * * * * wget –no-check-certificate -b -N -q -O /var/www/map.canonn.technology/git-repos/CanonnED3D-All-Map/data/csvCache/bmDataCache.csv ''
*/15 * * * * wget –no-check-certificate -b -N -q -O /var/www/map.canonn.technology/git-repos/CanonnED3D-All-Map/data/csvCache/btDataCache.csv ''
*/15 * * * * wget –no-check-certificate -b -N -q -O /var/www/map.canonn.technology/git-repos/CanonnED3D-All-Map/data/csvCache/fgDataCache.csv ''
*/15 * * * * wget –no-check-certificate -b -N -q -O /var/www/map.canonn.technology/git-repos/CanonnED3D-All-Map/data/csvCache/fmDataCache.csv ''
*/15 * * * * wget –no-check-certificate -b -N -q -O /var/www/map.canonn.technology/git-repos/CanonnED3D-All-Map/data/csvCache/genDataCache.csv ''
*/15 * * * * wget –no-check-certificate -b -N -q -O /var/www/map.canonn.technology/git-repos/CanonnED3D-All-Map/data/csvCache/grDataCache.csv ''
*/15 * * * * wget –no-check-certificate -b -N -q -O /var/www/map.canonn.technology/git-repos/CanonnED3D-All-Map/data/csvCache/gyDataCache.csv ''
*/15 * * * * wget –no-check-certificate -b -N -q -O /var/www/map.canonn.technology/git-repos/CanonnED3D-All-Map/data/csvCache/hdDataCache.csv ''
*/15 * * * * wget –no-check-certificate -b -N -q -O /var/www/map.canonn.technology/git-repos/CanonnED3D-All-Map/data/csvCache/lsDataCache.csv ''
*/15 * * * * wget –no-check-certificate -b -N -q -O /var/www/map.canonn.technology/git-repos/CanonnED3D-All-Map/data/csvCache/msDataCache.csv ''
*/15 * * * * wget –no-check-certificate -b -N -q -O /var/www/map.canonn.technology/git-repos/CanonnED3D-All-Map/data/csvCache/tbDataCache.csv ''
*/15 * * * * wget –no-check-certificate -b -N -q -O /var/www/map.canonn.technology/git-repos/CanonnED3D-All-Map/data/csvCache/tsDataCache.csv ''
*/15 * * * * wget –no-check-certificate -b -N -q -O /var/www/map.canonn.technology/git-repos/CanonnED3D-All-Map/data/csvCache/ussDataCache.csv ''