#!/bin/bash

# Grabs all the updated CSV Files from Google and stores them
# For use by Canonn on our Webserver for caching purposes.... really not useful for anyone else


######################
# POI & GNOSIS CACHE #
######################
wget –no-check-certificate -b -N -q -O /var/www/canonn.tech/git_repo/CanonnED3D-Map/Source/data/csvCache/poiDataCache.csv 'https://docs.google.com/spreadsheets/d/e/2PACX-1vTind7brsm0s_aD8iH-zyJCNvPxy5PwFaGLVAIR28VGNjlj4vaAHJzosar3_4J4ZnOrioBx-BcLMHa9/pub?gid=0&single=true&output=csv'
################
# SYSTEM CACHE #
################
wget –no-check-certificate -b -N -q -O /var/www/canonn.tech/git_repo/CanonnED3D-Map/Source/data/csvCache/bmSystemCache.csv 'https://docs.google.com/spreadsheets/d/e/2PACX-1vQ8QvI-CQYlDWcfyXonkisu9yUnlPNPQHgHt1_o3n0NjsFMNlRWy9EgVqFTZm8LTOWXgXp2c70GMGsr/pub?gid=0&single=true&output=csv' 
wget –no-check-certificate -b -N -q -O /var/www/canonn.tech/git_repo/CanonnED3D-Map/Source/data/csvCache/btSystemCache.csv 'https://docs.google.com/spreadsheets/d/e/2PACX-1vR_8aPljkn5ZNMUXccsySkQCDFKZlhr6WD_R3eu61fpIW-LXf4airdgzzOqgjFUkTO20SX7l7JXjYFP/pub?gid=0&single=true&output=csv' 
wget –no-check-certificate -b -N -q -O /var/www/canonn.tech/git_repo/CanonnED3D-Map/Source/data/csvCache/fgSystemCache.csv 'https://docs.google.com/spreadsheets/d/e/2PACX-1vSvvfHhzfAeDiBuQoDrnmUgeh57XjeRXWJcVe-48BW0ugulqUMDrN7AoOtY96Suk7uQHv2tcZ_ek0ty/pub?gid=1615049300&single=true&output=csv' 
wget –no-check-certificate -b -N -q -O /var/www/canonn.tech/git_repo/CanonnED3D-Map/Source/data/csvCache/fmSystemCache.csv 'https://docs.google.com/spreadsheets/d/e/2PACX-1vSlszRWQ2eTUxzzM2AxsCOnQ2Rg7C8zBx_YJGUR1BdpK-wwXv9DpeueiWEQPJTVF9AI5J3LExucx5Lh/pub?gid=827706542&single=true&output=csv' 
wget –no-check-certificate -b -N -q -O /var/www/canonn.tech/git_repo/CanonnED3D-Map/Source/data/csvCache/genSystemCache.csv 'https://docs.google.com/spreadsheets/d/e/2PACX-1vRmBzKonapgMMWeT-zc26w8xCNFvK_5l1F3fwF0_af7awhL0MNUGOKnIq4FSoEXe8TtD5HeZd4OuAUu/pub?gid=1451709127&single=true&output=csv' 
wget –no-check-certificate -b -N -q -O /var/www/canonn.tech/git_repo/CanonnED3D-Map/Source/data/csvCache/grSystemCache.csv 'https://docs.google.com/spreadsheets/d/e/2PACX-1vTYml1O4Qt2bDn9hnFJe1SeN0atyahK6dWBftGvW1YJ8b6JHBUF5WvL015_fmZF6oGkqVOGzl3mJqVI/pub?gid=756384248&single=true&output=csv' 
wget –no-check-certificate -b -N -q -O /var/www/canonn.tech/git_repo/CanonnED3D-Map/Source/data/csvCache/gySystemCache.csv 'https://docs.google.com/spreadsheets/d/e/2PACX-1vR70NkI6yp_9jwC_6FseydVBs22MrX3aWONiy4xvfx8EHz8pmI4mo1s25at8ihs3GrXRbEdoQDepy1m/pub?gid=962735107&single=true&output=csv' 
wget –no-check-certificate -b -N -q -O /var/www/canonn.tech/git_repo/CanonnED3D-Map/Source/data/csvCache/hdSystemCache.csv 'https://docs.google.com/spreadsheets/d/e/2PACX-1vSEVt8eYMJgd5vXfCMiExWc23D1G5G0DCEfs5A6N3AQGupAp1KslajioBZgB0IGiMd7MR_Ur3RPsv39/pub?gid=1013174415&single=true&output=csv' 
wget –no-check-certificate -b -N -q -O /var/www/canonn.tech/git_repo/CanonnED3D-Map/Source/data/csvCache/lsSystemCache.csv 'https://docs.google.com/spreadsheets/d/e/2PACX-1vQhAk6nZswglFQVpNpPfUwJNS0ifkN4sOLHsQeCmIrMiQM01N6tPEyvKqcHUnD-IRSO7a9bTCwa4tR6/pub?gid=220546017&single=true&output=csv' 
wget –no-check-certificate -b -N -q -O /var/www/canonn.tech/git_repo/CanonnED3D-Map/Source/data/csvCache/msSystemCache.csv 'https://docs.google.com/spreadsheets/d/e/2PACX-1vRSTnVpcJPN1yn5bcCrI3vYocYUVX08jcfsEUbbY3-u9G_uBqfGlllMu6gSa5LGt4sEO_fh3G5H2G0r/pub?gid=1120806489&single=true&output=csv' 
wget –no-check-certificate -b -N -q -O /var/www/canonn.tech/git_repo/CanonnED3D-Map/Source/data/csvCache/tbSystemCache.csv 'https://docs.google.com/spreadsheets/d/e/2PACX-1vTyFAaquLIKghHUiN-FJaku3yzGw6f_lMFQHUPqLVoCfRE8gtlWb88mMpLhoTXjLhmot0m8w9Ol5cPs/pub?gid=1613553729&single=true&output=csv' 
wget –no-check-certificate -b -N -q -O /var/www/canonn.tech/git_repo/CanonnED3D-Map/Source/data/csvCache/tsSystemCache.csv 'https://docs.google.com/spreadsheets/d/e/2PACX-1vSYvun070NwUTxemgq05M5jSrFdbJXDd3unpohkt9WhlGjHfY67odla933_HWT1xe8X5-Ebq73gz61e/pub?gid=926585382&single=true&output=csv' 
wget –no-check-certificate -b -N -q -O /var/www/canonn.tech/git_repo/CanonnED3D-Map/Source/data/csvCache/ussSystemCache.csv 'https://docs.google.com/spreadsheets/d/e/2PACX-1vQM1TtPi_18DZ0hIJ2dW44F0BpW6_igwfXYbTuZS3IQZUIjmZLY5ElZFuWpLES7iBQNDsVs8vwXwJ1n/pub?gid=1735934279&single=true&output=csv'
wget –no-check-certificate -b -N -q -O /var/www/canonn.tech/git_repo/CanonnED3D-Map/Source/data/csvCache/gsSystemCache.csv 'https://docs.google.com/spreadsheets/d/e/2PACX-1vTmkwaJkf8uvn0GVv-h2jnNv141BvfhoOcS1h7Et3ojE-HqYZugJp3d9xYKMjrlibl-fCg4HNFLwfIe/pub?gid=756384248&single=true&output=csv'
wget –no-check-certificate -b -N -q -O /var/www/canonn.tech/git_repo/CanonnED3D-Map/Source/data/csvCache/oiSystemCache.csv 'https://docs.google.com/spreadsheets/d/e/2PACX-1vSzYSv8ieUZE1ykSNZ0l2FkXK1moKJ_mNZrvoeeoAsweLyfRKqvhJROakwftcLwGH2Fh20fBL605kbE/pub?gid=0&single=true&output=csv'
wget –no-check-certificate -b -N -q -O /var/www/canonn.tech/git_repo/CanonnED3D-Map/Source/data/csvCache/gbSystemCache.csv 'https://docs.google.com/spreadsheets/d/e/2PACX-1vTVmk7Kggb3USr2Q18cFO9JrTY_mUehu6IUEgN_elsd_F1l3TS3uggOlc_P9aLluoX6AQCgRFa9rnNe/pub?gid=756384248&single=true&output=csv'
##############
# DATA CACHE #
##############
wget –no-check-certificate -b -N -q -O /var/www/canonn.tech/git_repo/CanonnED3D-Map/Source/data/csvCache/bmDataCache.csv 'https://docs.google.com/spreadsheets/d/e/2PACX-1vT5BZ9lC7vqmpwIsGCGH-d1uQIOIdFEZQFyUv1MXPSsRKFd1_QS8loG1a4SQurINFC6W48yecNYX1n8/pub?gid=0&single=true&output=csv' 
wget –no-check-certificate -b -N -q -O /var/www/canonn.tech/git_repo/CanonnED3D-Map/Source/data/csvCache/btDataCache.csv 'https://docs.google.com/spreadsheets/d/e/2PACX-1vRdEQQByWyU8MlzfJw9SzEsaM9c_zDV_RJ49Fiox842EEELrUHpMPexLYhjqNB8SOzB564jJ_oLdBx2/pub?gid=0&single=true&output=csv' 
wget –no-check-certificate -b -N -q -O /var/www/canonn.tech/git_repo/CanonnED3D-Map/Source/data/csvCache/fgDataCache.csv 'https://docs.google.com/spreadsheets/d/e/2PACX-1vSkplnC17_skeKQP4KA-f1Cg7e1i4Sizw3wyBhHxSQXXPqFMwe817YcJLcyjczmh8gjYswKquRE8Kf9/pub?gid=0&single=true&output=csv' 
wget –no-check-certificate -b -N -q -O /var/www/canonn.tech/git_repo/CanonnED3D-Map/Source/data/csvCache/fmDataCache.csv 'https://docs.google.com/spreadsheets/d/e/2PACX-1vQ7yJ1oi39bonW8vioR_ZvVnuGlLiSnMkFkB_Fm8gpcbG7zwfzIrqhe9Dd8mEyXpnBTLP1Y3cUUBv3R/pub?gid=0&single=true&output=csv' 
wget –no-check-certificate -b -N -q -O /var/www/canonn.tech/git_repo/CanonnED3D-Map/Source/data/csvCache/genDataCache.csv 'https://docs.google.com/spreadsheets/d/e/2PACX-1vSGNiGE2bg2jMYdkbY85vaWsTeEqEBfPMnKMrNplpCd_nfpvwAhxrFq0of9pLt2m6biyz-_MYnSa6Io/pub?gid=0&single=true&output=csv' 
wget –no-check-certificate -b -N -q -O /var/www/canonn.tech/git_repo/CanonnED3D-Map/Source/data/csvCache/grDataCache.csv 'https://docs.google.com/spreadsheets/d/e/2PACX-1vTSvkdtHr0SbM4dYOCsDalp1hRilWt2I5Hz1l2OIgbfR8Hs-lOCat_ZUyhyBnuv9R9rXz9vnhaYif2-/pub?gid=0&single=true&output=csv' 
wget –no-check-certificate -b -N -q -O /var/www/canonn.tech/git_repo/CanonnED3D-Map/Source/data/csvCache/gyDataCache.csv 'https://docs.google.com/spreadsheets/d/e/2PACX-1vSrkVndsyRh4HGTsPcyCsuyyrzDbGCc2US69p6rcWCcOwh5MTk7ujj0ZkJsMHQYRQ1aHEUVfLIRTPx1/pub?gid=0&single=true&output=csv' 
wget –no-check-certificate -b -N -q -O /var/www/canonn.tech/git_repo/CanonnED3D-Map/Source/data/csvCache/lsDataCache.csv 'https://docs.google.com/spreadsheets/d/e/2PACX-1vTNfdgLCazewrFekmEvQcr2AITeGaopFN5NrH1L5Ajy06d90dyuWwlwGs4uDqK7JfNR3IZLS-wFqEar/pub?gid=0&single=true&output=csv' 
wget –no-check-certificate -b -N -q -O /var/www/canonn.tech/git_repo/CanonnED3D-Map/Source/data/csvCache/msDataCache.csv 'https://docs.google.com/spreadsheets/d/e/2PACX-1vRYM-AYQcU6f6M-mU66_JyCnXUaxu9vrO03LblPtajcJmRstwMKmbjMKPsEQFFnR7ZydBnMeCCPYiG_/pub?gid=0&single=true&output=csv' 
wget –no-check-certificate -b -N -q -O /var/www/canonn.tech/git_repo/CanonnED3D-Map/Source/data/csvCache/tbDataCache.csv 'https://docs.google.com/spreadsheets/d/e/2PACX-1vTCGOwaRT8ESad9j0GAQ7tMMNj8ObxipFW8fop3eaZ-HoCVo_k9dQsHVvs1oFvARrY5SC6o4uDAWKQA/pub?gid=290263950&single=true&output=csv' 
wget –no-check-certificate -b -N -q -O /var/www/canonn.tech/git_repo/CanonnED3D-Map/Source/data/csvCache/tsDataCache.csv 'https://docs.google.com/spreadsheets/d/e/2PACX-1vR4-rhi1p4BU7AlOSj7_78Kvk5Ox6vb39vzzlWU3yI-dqlaLxk-CFLWvAFKc-J7WhomFiQ_u0P7Stxz/pub?gid=0&single=true&output=csv'
wget –no-check-certificate -b -N -q -O /var/www/canonn.tech/git_repo/CanonnED3D-Map/Source/data/csvCache/ussDataCache.csv 'https://docs.google.com/spreadsheets/d/e/2PACX-1vSItisRz94_hJ-BHBppvie7hMghwHNBokehxii24XyA2sSkghITOGgbZR_2jlF5sdC5V_ZtR92e_DWq/pub?gid=0&single=true&output=csv'
wget –no-check-certificate -b -N -q -O /var/www/canonn.tech/git_repo/CanonnED3D-Map/Source/data/csvCache/nhssDataCache.csv 'https://docs.google.com/spreadsheets/d/e/2PACX-1vRFtumwllKnzV_edHFtrb8rX6lDO3lv7LR9M0ucQVo-fNhTZKI46SFHkGsTYPvVtHG84QT72LB5QXGa/pub?gid=0&single=true&output=csv'
wget –no-check-certificate -b -N -q -O /var/www/canonn.tech/git_repo/CanonnED3D-Map/Source/data/csvCache/gsDataCache.csv 'https://docs.google.com/spreadsheets/d/e/2PACX-1vQHNaxFAo9K-_3f37jVF5-_rBJUdl9d4FtRQgQWBCDEVZTfvERdwZoGss3z3D0CZ4xbsLWDf468CxS6/pub?gid=0&single=true&output=csv'
wget –no-check-certificate -b -N -q -O /var/www/canonn.tech/git_repo/CanonnED3D-Map/Source/data/csvCache/oiDataCache.csv 'https://docs.google.com/spreadsheets/d/e/2PACX-1vS7G5Szx3UIQbJqxDw2ESNAxefNTX2Ha7Y1QMyMA1DZg4mXjI0_ZfFVzflZEu1uMe6pX0lau36iqjgG/pub?gid=0&single=true&output=csv'
wget –no-check-certificate -b -N -q -O /var/www/canonn.tech/git_repo/CanonnED3D-Map/Source/data/csvCache/gbDataCache.csv 'https://docs.google.com/spreadsheets/d/e/2PACX-1vT9SqkOdvO-y92jOwdHZoVEdO0t98Nf_KrzkBzRya9qJmDmIi70H6NH0QVFwLrywdl45tjsSeJvfGmQ/pub?gid=0&single=true&output=csv'
